name: Destroy Azure Resources

on:
  workflow_dispatch:
  schedule:
    - cron: "30 2 * * *"

env:
  RESOURCE_GROUP: rg-warhammerAppGR

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Delete Resource Group if exists
      run: |
        EXISTS=$(az group exists --name $RESOURCE_GROUP)

        echo "Resource group exists: $EXISTS"

        if [ "$EXISTS" = "true" ]; then
          echo "Deleting resource group..."
          az group delete -n $RESOURCE_GROUP --yes --no-wait
          echo "Delete command sent."
        else
          echo "Nothing to delete."
        fi